django/honeycomics/accounts/urls.py
# accounts/urls.py

from django.urls import path
from .views import SignUpView

name = "accounts"
urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

django/honeycomics/honeycomics/urls.py
# honeycomics/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pricing.urls"), name="pricing"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
]

django/honeycomics/pricing/urls.py
# pricing/urls.py

from django.urls import path
from .views import PlanView, PlanDetailView, CreateCBSubscriptionView, WebhookView, SubscriptionView

app_name = "pricing"

urlpatterns = [
    path("plans", PlanView.as_view(), name="plans"),
    path("plan/<int:pk>/", PlanDetailView.as_view(), name="plan-detail"),
    path(
        "api/generate_checkout_new_url",
        CreateCBSubscriptionView.as_view(),
    ),
    path("webhooks", WebhookView.as_view()),
    path("subscription", SubscriptionView.as_view(), name="subscription"),

]

django/honeycomics/accounts/models.py
from django.db import models

# Create your models here.

django/honeycomics/pricing/models.py
# pricing/models.py

from django.db import models
from django.conf import settings

User = settings.AUTH_USER_MODEL


class Plan(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)

    def __str__(self):
        return self.name


class PlanPrice(models.Model):
    price_id = models.CharField(max_length=255, primary_key=True)
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    price = models.IntegerField()
    currency = models.CharField(max_length=255, default="USD")
    period = models.CharField(max_length=255)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.period} {self.plan.name} {self.currency} plan"


class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subscribed_to = models.ForeignKey(PlanPrice, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.user.username} {self.subscribed_to.plan.name}"

django/honeycomics/accounts/forms.py
# accounts/forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required. 30 characters or fewer.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Required. 30 characters or fewer.')
    email = forms.EmailField(required=True, help_text='Required. Enter a valid email address.')

    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email')

django/honeycomics/accounts/views.py
# accounts/views.py

from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .forms import UserForm


class SignUpView(CreateView):
    form_class = UserForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

django/honeycomics/pricing/views.py
# pricing/views.py

import json
import chargebee
from .models import Plan, PlanPrice, Subscription
from django.views.generic import View, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseForbidden
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User

# US region IP addresses
ALLOWED_IPS = [
    '3.209.65.25',
    '3.215.11.205',
    '3.228.118.137',
    '3.229.12.56',
    '3.230.149.90',
    '3.231.198.174',
    '3.231.48.173',
    '3.233.249.52',
    '18.210.240.138',
    '18.232.249.243',
    '34.195.242.184',
    '34.206.183.55',
    '35.168.199.245',
    '52.203.173.152',
    '52.205.125.34',
    '52.45.227.101',
    '54.158.181.196',
    '54.163.233.122',
    '54.166.107.32',
    '54.84.202.184',
]


class PlanView(LoginRequiredMixin, ListView):
    model = Plan
    context_object_name = "plans"
    template_name = "pricing/plans.html"


class PlanDetailView(LoginRequiredMixin, DetailView):
    model = Plan
    context_object_name = "plan"
    template_name = "pricing/plan_detail.html"

    def get_context_data(self, **kwargs):
        context = super(PlanDetailView, self).get_context_data()
        context["plan_prices"] = PlanPrice.objects.filter(plan=self.get_object())
        return context


class CreateCBSubscriptionView(View):
    def post(self, request, *args, **kwargs):
        try:
            price_id = request.POST.get("price_id")
            # Configure Chargebee
            chargebee.configure('CHARGEBEE_API_KEY', 'CHARGEBEE_SITE')

            # Use the received price_id in the checkout request
            result = chargebee.HostedPage.checkout_new_for_items(
                {
                    "subscription_items": [
                        {"item_price_id": price_id},
                    ],
                    "customer": {
                        "first_name": request.user.first_name,
                        "last_name": request.user.last_name,
                        "email": request.user.email,
                    }
                }
            )

            # Extract hosted_page from the result
            hosted_page = result._response["hosted_page"]
            # Return the hosted_page data as JSON response
            return JsonResponse(hosted_page)
        except json.JSONDecodeError:
            return JsonResponse(
                {"error": "Invalid JSON data in the request."}, status=400
            )


@method_decorator(csrf_exempt, name="dispatch")
class WebhookView(View):
    def post(self, request, *args, **kwargs):
        try:
            remote_ip = request.META.get('REMOTE_ADDR', None)
            if remote_ip in ALLOWED_IPS:
                event = json.loads(request.body)
                if event["event_type"] == "subscription_created":
                    content = event["content"]
                    email = content["customer"]["email"]
                    user = User.objects.get(email=email)
                    item_price_id = content["subscription"]["subscription_items"][0]["item_price_id"]
                    item_price = PlanPrice.objects.get(price_id=item_price_id)
                    Subscription.objects.create(user=user, subscribed_to=item_price)
                    return JsonResponse({"status": "success"}, status=200)
                else:
                    print("Unhandled event type")
                    return JsonResponse({"status": "success"}, status=200)
            else:
                return HttpResponseForbidden("Access denied: Request from unauthorized IP.")
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=500)


class SubscriptionView(LoginRequiredMixin, ListView):
    model = Subscription
    template_name = 'pricing/subscription.html'
    context_object_name = 'subscription'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subscription'] = Subscription.objects.filter(user=self.request.user).order_by('-created_at').first()
        return context

django/honeycomics/pricing/templates/pricing/plan_detail.html
<!-- pricing/templates/pricing/plan_detail.html -->

{% extends "base.html" %} {% block title %} Buy Plan {% endblock title%} {% block content %}
<div class="card-deck my-5 p-3">
    <h5>{{plan.name}}</h5>
    <p>{{plan.description}}</p>

    {% for price in plan_prices %}
    <div class="card my-3">
        <div class="card-body">
            <h5>{{price.period}} : {{price.currency}} {{ price.price }}</h5>
            <button class="checkout-button btn btn-primary" data-price="{{ price.price_id }}">
                Checkout
            </button>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

django/honeycomics/pricing/templates/pricing/plans.html
<!-- pricing/templates/pricing/plans.html -->

{% extends "base.html" %} {% block title %} Plans {% endblock title%} {% block content %}
<div class="row my-5">
    {% for plan in plans %}
    <div class="col card m-3 p-3">
        <div>
            <h5>{{plan.name}}</h5>
            <p>{{plan.description}}</p>
            <a href="{% url 'pricing:plan-detail' plan.id %}" class="btn btn-primary">View Detail</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

django/honeycomics/pricing/templates/pricing/subscription.html
<!-- ../pricing/templates/pricing/subscription.html -->

{% extends "base.html" %} {% block title %} Success {% endblock title%} {% block content %}
<div class="alert alert-success my-5" role="alert">
    {% if subscription %} Thanks for subscribing! You are subscribed to
    <strong>{{ subscription.subscribed_to }}</strong> {% else %} Please subscribe to any
    <a href="{% url 'pricing:plans' %}"> plans</a>
    {% endif %}
</div>
{% endblock content %}

django/honeycomics/templates/base.html
<!-- base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    {% load static %}
    <!-- Bootstrap CSS -->
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
            crossorigin="anonymous"
    />
    <title>{% block title %} {% endblock %}</title>
    <!-- Chargebee JS -->
    <script src="https://js.chargebee.com/v2/chargebee.js"></script>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Bootstrap JS -->
    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
            crossorigin="anonymous"
    ></script>
</head>

<!-- templates/base.html-->

<body>
<div class="container my-5">
    <div class="d-flex justify-content-between flex-row">
        <h1>
            <a style="text-decoration:none; " class="text-dark" href="{% url 'pricing:plans' %}"
            >Honey Comics</a
            >
        </h1>
        <div>
            {% if user.is_authenticated %}
            <div class="d-flex column-gap-4 flex-row">
                <h4>Hi {{ user.username }}</h4>
                <a class="btn btn-dark" href="{% url 'logout' %}">Log out</a>
            </div>
            {% else %}
            <a class="btn btn-dark" href="{% url 'login' %}">Log In</a>
            <a class="btn btn-dark" href="{% url 'signup' %}">Sign Up</a>
            {% endif %}
        </div>
    </div>
    {% block content %}{% endblock %}
</div>
<script src="{% static 'pricing/checkout.js' %}"></script>
</body>

</html>